const mockData = {
  nomeDaFeira: "Feira Mockada",
  razãoSocial: "NicksModa LTDA",
  nomeFantasia: "Nicks",
  CNPJ: "48.158.983/0001-15",
  enderecoEmpreendimento: "Avenida Eldes Scherrer Souza, nº 2.162, Loja 203 A ",
  bairroEmpreendimento: "Colina de Laranjeiras",
  cidadeEmpreendimento: "Serra",
  ufEmpreendimento: "ES",
  cepEmpreendimento: "29.167-080",
  telefoneEmpreendimento: "27 99765-5848",
  emailEmpreendimento: "nicksmodaintima@hotmail.com",
  qtdEmpregados: "01",
  dataAbertura: "03/01/2022",
  nome: "Elizabeth Vaccari Santos",
  CPF: "098.899.427-55",
  enderecoResponsavel: "Peroba do Campo, R, 10",
  bairroResponsavel: "José de Anchieta",
  cidadeResponsavel: "Serra",
  ufResponsavel: "ES",
  cepResponsavel: "29.162-490",
  telefoneResponsavel: "27 997655848",
  emailResponsavel: "nicksmodaintima@hotmail.com",
  nomeDoProjeto: "Projeto Tal",
  tipoDeAreaLivre: true,
  tipoDeAreaMontada: true,
  metragemAreaLivre: "2500 m²",
  metragemAreaMontada: "1500 m²",
  identificaçãoDoEstande: "Estande Cicrano",
  dataInicio: "20/11/2023",
  dataFim: "20/12/2023",
  localDaFeira: "Pavilhão de Carapina",
  percentualDeContrapartidaDoCliente: "30%",
  valorContrapartidaCliente: "250.000,00",
  dataLimiteInscricao: "10/10/2023",
};

export default mockData;
